load("//notes/core/jni:defs.bzl", "cc_core_jni_lib")

cc_core_jni_lib(
    name = "mapping",
    srcs = [
        "jvm_class.cpp",
        "to_jvm.cpp",
        "to_native.cpp",
    ],
    hdrs = [
        "jvm_class.hpp",
        "to_jvm.hpp",
        "to_native.hpp",
    ],
)
