load("//tools/cpp:rules.bzl", "cc_headers_lib")
load("//notes/core/cpp:visibility.bzl", "HDRS_CONSUMERS")

cc_headers_lib(
    name = "sample_bind",
    hdrs = [
        "sample_bind.hpp",
    ],
    visibility = HDRS_CONSUMERS,
)
