load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary")

kt_jvm_binary(
    main_class = "com.fondesa.notes.cli.AppKt",
    name = "app",
    srcs = [
        "App.kt",
    ],
    deps = [
    ],
)
