package(default_visibility = ["//notes/core/jni:__subpackages__"])

alias(
    name = "sample_bind",
    actual = "//notes/core/cpp/src:sample_bind",
)

alias(
    name = "notes",
    actual = "//notes/core/cpp/src/notes:notes",
)
