package(default_visibility = ["//notes/core/jni:__subpackages__"])

alias(
    name = "sample_bind",
    actual = "//notes/core/cpp/src:sample_bind",
)

alias(
    name = "note",
    actual = "//notes/core/cpp/src/note:note",
)

alias(
    name = "draft",
    actual = "//notes/core/cpp/src/draft:draft",
)
