load("//tools/cpp:rules.bzl", "cc_impl_lib")

cc_impl_lib(
    name = "sample_bind",
    srcs = [
        "sample_bind.cpp",
    ],
    deps = [
        "//notes/core/cpp/include:sample_bind",
    ],
)
