load("//tools/cpp:rules.bzl", "cc_impl_lib")
load("//notes/core/cpp:visibility.bzl", "IMPL_CONSUMERS")

cc_impl_lib(
    name = "sample_bind",
    hdrs = [
        "sample_bind.hpp"
    ],
    srcs = [
        "sample_bind.cpp",
    ],
    visibility = [
        "//notes/core/cpp/public:__pkg__"
    ],
    deps = [
    ],
)
