load("//tools/jvm:defs.bzl", "jvm_lib")
load("//notes/core/jvm:visibility.bzl", "PUBLIC_CONSUMERS")

jvm_lib(
    name = "notes",
    srcs = [
        "Draft.kt",
        "NotesInteractor.kt",
    ],
    visibility = PUBLIC_CONSUMERS,
)
