#android_binary(
#    name = "app",
##    custom_package = "com.foo",
#    manifest = "AndroidManifest.xml",
##    manifest_values = {
##        "minSdkVersion": "21",
##        "targetSdkVersion": "29",
##    },
#    srcs = ["/com/fondesa/notes/cli/MainActivity.kt"],
#    resource_files = glob(["res/**"]),
#    deps = [
#    ]
#)