package(default_visibility = [
    "//notes/core/jvm:__subpackages__",
    # TODO: remove this when possible
    "//notes/cli/src/com/fondesa/notes/cli:__pkg__",
])

alias(
    name = "jni_sample_bind",
    actual = "//notes/core/jni/src/exports:jni_sample_bind",
)

alias(
    name = "jni_notes_interactor",
    actual = "//notes/core/jni/src/exports:jni_notes_interactor",
)
