load("//tools/linters/internal/buildifier:rules.bzl", "buildifier")

buildifier(
    name = "buildifier_check",
    mode = "check",
    visibility = ["//tools/linters:__pkg__"],
)

buildifier(
    name = "buildifier_format",
    mode = "format",
    visibility = ["//tools/linters:__pkg__"],
)
