load("//tools/cpp:rules.bzl", "cc_impl_lib")
load("//notes/core/cpp:visibility.bzl", "PUBLIC_CONSUMERS")

cc_impl_lib(
    name = "note",
    srcs = [
        "note.cpp",
    ],
    hdrs = [
        "note.hpp",
    ],
    visibility = PUBLIC_CONSUMERS,
)
