alias(
    name = "bazel_check",
    actual = "//tools/linters/internal:buildifier_check",
    visibility = ["//visibility:public"],
)

alias(
    name = "bazel_format",
    actual = "//tools/linters/internal:buildifier_format",
    visibility = ["//visibility:public"],
)

alias(
    name = "cpp_format",
    actual = "//tools/linters/internal/clang:clang_format",
    visibility = ["//visibility:public"],
)