load("//tools/cpp:rules.bzl", "cc_headers_lib")
load("//notes/core/cpp:visibility.bzl", "HDRS_CONSUMERS")

cc_headers_lib(
    name = "time",
    hdrs = [
        "clock.hpp",
        "time_format.hpp",
    ],
    visibility = HDRS_CONSUMERS,
)
