load("//notes/core/jni:defs.bzl", "cc_core_jni_lib")

cc_core_jni_lib(
    name = "jni_sample_bind",
    srcs = [
        "jni_sample_bind.cpp",
    ],
    is_public = True,
    deps = [
        "//notes/core/cpp/public:sample_bind",
    ],
)
