load("//notes/core/cpp:defs.bzl", "cc_core_lib")
load("//notes/core/cpp:visibility.bzl", "PUBLIC_CONSUMERS")

cc_core_lib(
    name = "draft",
    srcs = [
        "draft.cpp",
    ],
    hdrs = [
        "draft.hpp",
    ],
    visibility = PUBLIC_CONSUMERS,
)
