load("//notes/core/cpp:defs.bzl", "cc_core_lib")

cc_core_lib(
    name = "time",
    srcs = [
        "clock_impl.cpp",
        "clock_impl.hpp",
        "time_format.cpp",
    ],
    hdrs = [
        "clock.hpp",
        "time_format.hpp",
    ],
)
