#load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
#load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

java_library(
    name = "prova",
    srcs = [
        "Foo.java",
    ],
    deps = [
    ],
)
