load("//notes/core/cpp:defs.bzl", "cc_core_lib")

cc_core_lib(
    name = "notes",
    srcs = [
        "draft.cpp",
        "note.cpp",
        "notes_interactor_impl.cpp",
        "notes_interactor_impl.hpp",
    ],
    hdrs = [
        "draft.hpp",
        "note.hpp",
        "notes_interactor.hpp",
    ],
    is_public = True,
)
