load("//notes/core/cpp:defs.bzl", "cc_core_test")

cc_core_test(
    name = "time_test",
    srcs = [
        "clock_impl_test.cpp",
        "time_format_test.cpp",
    ],
    deps = [
        "//notes/core/cpp/src/time",
    ],
)
